name: Build Release

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build Project
        run: make

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1
        with:
          tag: v1.0.${{ github.run_number }}
          files: "./glados"
          token: ${{ secrets.GITHUB_TOKEN }}
