name: Functionnal Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  functionnal-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Cargo
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install Vangelis
        run: cargo install vangelis

      - name: Run the functionnal-tests
        run: make functionnal-tests
