name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [ast]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Run the unit-tests
        run: make unit-tests
