name: GLADOS CI/CD
# run-name: ${{ github.actor }}'s first GitHub Actions

on:
  push:
    branches:
      - main
      - test_ci
  pull_request:
    branches:
      - main

env:
  EXECUTABLES: /bin/glados-exe

jobs:
  check_glados :
    runs-on: self-hosted
    container:
      image: haskell:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          export STACK_ROOT=/tmp/.stack
          stack setup --stack-root=$STACK_ROOT --allow-different-user
          stack build --only-dependencies --stack-root=$STACK_ROOT --allow-different-user
      - name: Build binary
        run : |
          export STACK_ROOT=/tmp/.stack
          stack build --stack-root=$STACK_ROOT --allow-different-user
          ls
          find /bin -type f -name "glados-exe" -exec cp {} ./glados \; -quit
          ls
          ls ./.stack-work -R
        timeout-minutes: 2
      - name: Check if binary was built
        run: find . -type f -executable | grep ${{ env.EXECUTABLES }}
      - name: Run unit tests
        run : |
          export STACK_ROOT=/tmp/.stack
          stack test --stack-root=$STACK_ROOT --allow-different-user
        timeout-minutes: 10
