name: GLADOS CI/CD
run-name: ${{ github.actor }}'s first GitHub Actions

on:
  push:
    branches:
      - main
      - test_ci
  pull_request:
    branches:
      - main

env:
  EXECUTABLES: glados

jobs:
  check_program_compilation :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.5'
          enable-stack: true
      - name: Install dependencies
        run: stack setup && stack build --only-dependencies
      - name: Build binary
        run : make
        timeout-minutes: 2
      - name: Check if binary was built
        run: find . -type f -executable | grep ${{ env.EXECUTABLES }}

  run_uni_tests :
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.5'
          enable-stack: true
      - name: Install dependencies
        run: stack setup && stack build --only-dependencies
      - name: Run unit tests
        run: make tests_run
        timeout-minutes: 2
