name: GLADOS CI/CD
run-name: ${{ github.actor }}'s first GitHub Actions

on:
  push:
    branches:
      - main
      - test_ci
  pull_request:
    branches:
      - main

env:
  EXECUTABLES: /bin/glados-exe

jobs:
  check_program_compilation :
    runs-on: self-hosted
    container:
      image: haskell:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          export STACK_ROOT=/tmp/.stack
          stack setup --stack-root=$STACK_ROOT --allow-different-user
          stack build --only-dependencies --stack-root=$STACK_ROOT --allow-different-user
      - name: Build binary
        run : stack build --stack-root=$STACK_ROOT --allow-different-user
        timeout-minutes: 2
      - name: Check if binary was built
        run: find . -type f -executable | grep ${{ env.EXECUTABLES }}

  run_uni_tests :
    runs-on: self-hosted
    container:
      image: haskell:latest
    needs: [check_program_compilation]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          export STACK_ROOT=/tmp/.stack
          stack setup --stack-root=$STACK_ROOT --allow-different-user
          stack build --only-dependencies --stack-root=$STACK_ROOT --allow-different-user
      - name: Run unit tests
        run: stack test --stack-root=$STACK_ROOT --allow-different-user
        timeout-minutes: 2
