name: GLADOS CI/CD
# run-name: ${{ github.actor }}'s first GitHub Actions

on:
  push:
    branches:
      - main
      - test_ci
  pull_request:
    branches:
      - main

env:
  EXECUTABLES: /bin/glados-exe

jobs:
  check_glados :
    runs-on: self-hosted
    container:
      image: haskell:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          export STACK_ROOT=/tmp/.stack
          stack setup --stack-root=$STACK_ROOT --allow-different-user
          stack build --only-dependencies --stack-root=$STACK_ROOT --allow-different-user
      
      - name: Build binary
        run : |
          export STACK_ROOT=/tmp/.stack
          stack build --stack-root=$STACK_ROOT --allow-different-user
        timeout-minutes: 2

      - name: Check if binary was built
        run: |
          BINARY_PATH=$(find . -type f -executable | grep ${{ env.EXECUTABLES }})
          echo "BINARY_PATH=$BINARY_PATH" >> $GITHUB_ENV

      - name: Run unit tests
        run : |
          export STACK_ROOT=/tmp/.stack
          stack test --stack-root=$STACK_ROOT --allow-different-user
        timeout-minutes: 10

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: v1.0.${{ github.run_number }}
          files: ${{ env.BINARY_PATH }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true

